name: flutter_app1
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  contacts_service: ^0.3.0
  permission_handler: '^3.2.0'
  json_annotation: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  - res/images/material_design_4.jpg
  - res/images/products/tasche_00.png
  - res/images/products/tasche_01.png
  - res/images/products/tasche_02.png
  - res/images/products/tasche_03.png
  - res/images/products/tasche_04.png

  - res/images/fussball/logo/96x96/logo_bayer_04_leverkusen_96x96.png
  - res/images/fussball/logo/96x96/logo_borussia_moenchengladbach._96x96.png
  - res/images/fussball/logo/96x96/logo_bvb_dortmund_96x96.png
  - res/images/fussball/logo/96x96/logo_fc_augsburg_96x96.png
  - res/images/fussball/logo/96x96/logo_fc_bayern_96x96.png
  - res/images/fussball/logo/96x96/logo_fc_koeln_96x96.png
  - res/images/fussball/logo/96x96/logo_fc_schalke_04_96x96.png
  - res/images/fussball/logo/96x96/logo_fc_union_96x96.png
  - res/images/fussball/logo/96x96/logo_fortuna_duesseldorf_96x96.png
  - res/images/fussball/logo/96x96/logo_fsv_mainz_96x96.png
  - res/images/fussball/logo/96x96/logo_hertha_bsc_berlin_96x96.png
  - res/images/fussball/logo/96x96/logo_rb_leipzig_96x96.png
  - res/images/fussball/logo/96x96/logo_sc_freiburg_96x96.png
  - res/images/fussball/logo/96x96/logo_sc_paderborn_96x96.png
  - res/images/fussball/logo/96x96/logo_SGE_frankfurt_96x96.png
  - res/images/fussball/logo/96x96/logo_sv_werder_bremen_96x96.png
  - res/images/fussball/logo/96x96/logo_tsg_hoffenheim_96x96.png
  - res/images/fussball/logo/96x96/logo_vfl_wolfsburg_96x96.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
